### ISSUE TITLE
Throws Type error when proto location is outside cwd

### ISSUE THREAD

**Issue by kams451** [njpatel/grpcc#2]
[TypeError: Cannot read property 'ns' of null]

**Comment by njpatel** [comment]
Urgh, will take a look later today. Thanks for reporting!

**Comment by njpatel** [comment]
Actually, i just tried this, it seems to work fine for me even if the proto is on another drive entirely from my CWD. The `ns of null` error normally happens with there's an issue with the proto itself, or grpcc can't detech the package name etc.

If it's reasonable, could you put the proto file here? Otherwise you can email me (address on profile page), and i'll test it privately.

Cheers!

**Comment by kams451** [comment]
Thanks Nigel,
For looking into it. I will send you the details later this evening.
Yeah kinda weird, as i didn’t experience this before.  Have a good one.

Cheers,
Kams

**Comment by kams451** [comment]
lol, i hate phone auto correct. Neil my bad not Nigel :)

**Comment by njpatel** [comment]
Hah - I was wondering! Cheers, :+1:

**Comment by njpatel** [comment]
Hi Kams, did you have that example proto file that causes the issue?

**Comment by kalbasit** [comment]
It's not working for me either :( I tried with node v4 and v5 on Linux. Here's an [example proto](https://gist.github.com/kalbasit/c411a5b03a10edd9fd39d9fd4e80aec4) which is a combined version of [all of this proto files](https://github.com/publica-project/protobuf-defs/tree/master/logger) without the grpc-gateway annotations.

```

**Comment by ankurcha** [comment]
+1 Just to tag on to this thread:

```bash
 grpcc --proto $HOME/Projects/api/resource_registry.proto --address 127.0.0.1:8443 --insecure
TypeError: Cannot read property 'ns' of null
    at Object.load (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/index.js:101:28)
    at createClient (/usr/local/lib/node_modules/grpcc/lib/index.js:16:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/grpcc/bin/grpcc.js:30:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
➜  ~ head `which grpcc`
#!/usr/bin/env node --harmony

'use strict';

let program = require('commander');

let grpcc = require('../lib');

program
  .version("0.0.1")
```

**Comment by dcelasun** [comment]
Same thing here on Linux. Here's the proto file:

```
syntax="proto3";

package messages;

service Authentication {
    rpc Authenticate (AuthRequest) returns (AuthResponse) {}
}

message AuthRequest {
    string deviceId = 1;
}

message AuthResponse {
    bool success = 1;
    string token = 2;
}
```

and here's the error:

```
TypeError: Cannot read property 'ns' of null
    at Object.load (/home/me/.npm-global/lib/node_modules/grpcc/node_modules/grpc/src/node/index.js:124:28)
    at createClient (/home/me/.npm-global/lib/node_modules/grpcc/lib/index.js:16:21)
    at Object.<anonymous> (/home/me/.npm-global/lib/node_modules/grpcc/bin/grpcc.js:30:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

**Comment by aguerere** [comment]
I am having the same error on Linux:

```
TypeError: Cannot read property 'ns' of null
    at Object.load (/home/beto/temp/grpc/examples/node/node_modules/grpc/src/node/index.js:124:28)
    at Object.<anonymous> (/home/beto/temp/grpc/examples/node/dynamic_codegen/greeter_server.js:37:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

Tried with node 6.9.0 and 4.6.1 , same on both.

**Comment by ramtej** [comment]
+1 same here.. @linux

**Comment by ndandanov** [comment]
I am experiencing the same issue on Debian Testing:

```
TypeError: Cannot read property 'ns' of null
    at Object.load (/usr/lib/node_modules/grpcc/node_modules/grpc/src/node/index.js:124:28)
    at createClient (/usr/lib/node_modules/grpcc/lib/index.js:16:21)
    at Object.<anonymous> (/usr/lib/node_modules/grpcc/bin/grpcc.js:30:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

The protofile is this one https://github.com/grpc/grpc/blob/v1.0.0/examples/protos/helloworld.proto.

I installed Node.js with the script provided in https://deb.nodesource.com/setup_6.x. 
The Node.js version is v6.10.0.

Thank you!

**Comment by SamuelMaxwell** [comment]
I was having this issue when trying to use ~/path/to/file, it then work when using ../../path/to/file worked
