### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by cpenner-va** [njpatel/grpcc#27]
Cool tool! I can definitely see this being handy for testing some of my endpoints!

I'm getting this error; and unfortunately don't have the context to debug it myself,

```
Client@127.0.0.1:50051> client.getKeywords({}, pr)
TypeError: Cannot read property 'name' of null
    at __ (/usr/local/lib/node_modules/grpcc/node_modules/arguejs/argue.js:117:46)
    at Client.makeServerStreamRequest [as getKeywords] (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/src/client.js:559:16)
    at repl:1:8
    at ContextifyScript.Script.runInContext (vm.js:32:29)
    at REPLServer.defaultEval (repl.js:341:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:191:7)
```

This is in response to running getKeywords, which is implemented agains this proto;

```protobuf
service Keywords {
    rpc GetKeywords (KeywordQuery) returns (stream KeywordInfo) {}
}

message KeywordQuery {
    repeated string search_term = 1;
    repeated string taxonomies = 2;
    repeated string must_contain = 3;
    bool allow_nsfw = 4;
    string language = 5;
}
```

A basic "hello world" grpc worked fine, any ideas why this doesn't work?

My grpc server responds correctly to my java client so I'm confident the server is working.

**Comment by njpatel** [comment]
Do you mean `getKeywordSuggestions` ?

**Comment by cpenner-va** [comment]
Sorry, typo in my issue, but not the cause of the error :P

**Comment by netdragonboberb** [comment]
It's the "stream" statement. I had a similar issue and removed stream and grpcc returned a value. So I don't think grpcc supports that yet? It's not a solution to remove stream, but it does provide a temporary workaround for grpcc testing to remove stream from .proto, test, then put it back.

**Comment by njpatel** [comment]
Hi, sorry for the delay on this but everything with streams etc should work correctly with the latest release (v1.0.0) - check out the examples: https://github.com/njpatel/grpcc#examples . Cheers!

**Comment by jfyne** [comment]
@njpatel I am still seeing this problem with v1.1.0

```sh
grpcc -a 127.0.0.1:33000 -i -p service.proto

Connecting to dbm.DBM on 127.0.0.1:33000. Available globals:

  client - the client connection to DBM
    advertisers (Empty, callback) returns Advertiser

  printReply - function to easily print a unary call reply (alias: pr)
  streamReply - function to easily print stream call replies (alias: sr)
  createMetadata - convert JS objects into grpc metadata instances (alias: cm)

DBM@127.0.0.1:33000> client.advertisers({}, pr)
TypeError: Cannot read property 'name' of null
    at __ (/usr/lib/node_modules/grpcc/node_modules/arguejs/argue.js:117:46)
    at ServiceClient.Client.makeServerStreamRequest (/usr/lib/node_modules/grpcc/node_modules/grpc/src/client.js:670:14)
    at apply (/usr/lib/node_modules/grpcc/node_modules/lodash/lodash.js:499:17)
    at ServiceClient.wrapper (/usr/lib/node_modules/grpcc/node_modules/lodash/lodash.js:5356:16)
    at repl:1:8
    at ContextifyScript.Script.runInContext (vm.js:32:29)
    at REPLServer.defaultEval (repl.js:341:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
```
Proto
```
syntax = "proto3";

package dbm;

service DBM {
    rpc Advertisers(Empty) returns (stream Advertiser) {}
}

message Empty {}

message Advertiser {
    string ID = 1;
    string Name = 2;
    string Status = 3;
}
```
Any ideas?

**Comment by njpatel** [comment]
@jfyne what happens if you do:

```
client.advertisers({}).on('data', streamReply).on('status', streamReply);
```

?

**Comment by jfyne** [comment]
ah yes... that was dumb of me
