### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by underscoretang** [njpatel/grpcc#3]
/usr/local/lib/node_modules/grpcc/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at bindings (/usr/local/lib/node_modules/grpcc/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/src/client.js:54:31)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by njpatel** [comment]
Hi Steven, do you have an example protobuf file where this problem occurs?
