### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "options.filename" property must be of type string. Received type object

### ISSUE THREAD

**Issue by aep** [njpatel/grpcc#55]
this is not how you use eval?
```
aep@u8: grpcc --proto proto/0x.proto --insecure  --address 127.0.0.1:8080 --eval 'client.getIdentity({}, pr)'
TypeError [ERR_INVALID_ARG_TYPE]: The "options.filename" property must be of type string. Received type object
    at new Script (vm.js:57:13)
    at module.exports (/home/aep/.nvm/versions/node/v10.0.0/lib/node_modules/grpcc/node_modules/eval/eval.js:68:18)
    at init (/home/aep/.nvm/versions/node/v10.0.0/lib/node_modules/grpcc/lib/index.js:152:5)
    at prepareClient (/home/aep/.nvm/versions/node/v10.0.0/lib/node_modules/grpcc/lib/index.js:44:3)
    at createClient (/home/aep/.nvm/versions/node/v10.0.0/lib/node_modules/grpcc/lib/index.js:82:12)
    at Object.<anonymous> (/home/aep/.nvm/versions/node/v10.0.0/lib/node_modules/grpcc/bin/grpcc.js:35:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
```

**Comment by AlexanderBinkovsky** [comment]
same issue happens on  node v10.1.0, grpcc @1.1.3 grpc@1.11.3

**Comment by wawa19933** [comment]
I have an issue as well, when using `-x testRpc.js` option
- node v10.4.1, 
- grpcc @1.1.3 
- grpc@1.12.2

**Comment by vipkum2** [comment]
I am also getting same-
hax-vipkumar-1|~/gitRepo/grpcc$ ./bin/grpcc.js --insecure --proto ./test/test.proto --address 192.168.0.88:10161 --exec ./examples/unary.js
TypeError [ERR_INVALID_ARG_TYPE]: The "options.filename" property must be of type string. Received type object
    at new Script (vm.js:57:13)
    at module.exports (/home/vipkumar/gitRepo/grpcc/node_modules/eval/eval.js:68:18)
    at init (/home/vipkumar/gitRepo/grpcc/lib/index.js:152:5)
    at prepareClient (/home/vipkumar/gitRepo/grpcc/lib/index.js:44:3)
    at createClient (/home/vipkumar/gitRepo/grpcc/lib/index.js:82:12)
    at Object.<anonymous> (/home/vipkumar/gitRepo/grpcc/bin/grpcc.js:35:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
hax-vipkumar-1|~/gitRepo/grpcc$

**Comment by mrlequoctuan** [comment]
try this patch https://github.com/mrlequoctuan/grpcc/commit/e424f74cf39a4894b41f797b28a8224e38abd731
or just try my fork :)

**Comment by aep** [comment]
@mrlequoctuan your fork works nicely, but you have issues disabled. are you planning to release on npm?

**Comment by malcolmsgroves** [comment]
Using node 8 seems to be a valid workaround

**Comment by alex-lzl** [comment]
> try this patch [mrlequoctuan@e424f74](https://github.com/mrlequoctuan/grpcc/commit/e424f74cf39a4894b41f797b28a8224e38abd731)
> or just try my fork :)

Your fork saves the day for me! It also fixed unary callback (broken in 1.1.3 here). Thank you!

**Comment by Matan** [comment]
For anyone using the `node:10-alpine` docker and installing `grpcc` globally. Patch like this:
```
RUN apk add --no-cache --virtual .grpcc-patch curl git  \
    && cd /usr/local/share/.config/yarn/global/node_modules/grpcc \
    && curl -s https://github.com/mrlequoctuan/grpcc/commit/e424f74cf39a4894b41f797b28a8224e38abd731.patch | git apply \
    && apk del .grpcc-patch
```

**Comment by J7mbo** [comment]
Why is this still not merged or fixed?
