### ISSUE TITLE
 Error: 14 UNAVAILABLE: Connect Failed

### ISSUE THREAD

**Issue by satishdixit** [njpatel/grpcc#56]
{ Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (C:\Users\satish.sharma\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client.js:64:15)
    at C:\Users\satish.sharma\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client.js:583:15 code: 14, metadata: {}, details: 'Connect Failed' }

**Comment by mgolovatiy-atconsulting-ru** [comment]
my [issue:rror: 14 UNAVAILABLE: TCP Read failed](https://github.com/njpatel/grpcc/issues/71).
