### ISSUE TITLE
Cann't find 'node-v57-darwin-x64-unknown/grpc_node.node' module

### ISSUE THREAD

**Issue by koponkin** [njpatel/grpcc#58]
I've installed grpcc successfully 
```
sudo npm install -g grpcc
/usr/local/bin/grpcc -> /usr/local/lib/node_modules/grpcc/bin/grpcc.js
+ grpcc@1.1.3
updated 1 package in 4.057s
```

After that try to do any operation like `grpcc -v` ->
```
Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
Original error: Cannot find module '/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node'
    at Object.<anonymous> (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/grpc_extension.js:43:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:145:12)
    at Module._compile (module.js:652:30)
```

**Comment by olga-mir** [comment]
I had the same issue with node 10 and 8, but it worked for me on node `v6.14.0`
