### ISSUE TITLE
Error: Could not load file "[object Object]"

### ISSUE THREAD

**Issue by hayorov** [njpatel/grpcc#62]
Hello tried to use the util:
```
⇒  grpcc -p ab.proto -a 35.204.122.102:7050
Error: Could not load file "[object Object]"
    at Object.load (/Users/allexx/.nvm/versions/node/v8.9.1/lib/node_modules/grpcc/node_modules/grpc/index.js:149:11)
    at Object.deprecated [as load] (internal/util.js:52:15)
    at createClient (/Users/allexx/.nvm/versions/node/v8.9.1/lib/node_modules/grpcc/lib/index.js:57:21)
    at Object.<anonymous> (/Users/allexx/.nvm/versions/node/v8.9.1/lib/node_modules/grpcc/bin/grpcc.js:35:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
```

```ab.proto
syntax = "proto3";

import "hfc/protos/common/common.proto";

option go_package = "github.com/hyperledger/fabric/protos/orderer";
option java_package = "org.hyperledger.fabric.protos.orderer";

package orderer;

message BroadcastResponse {
    common.Status status = 1;
}

message SeekNewest { }

message SeekOldest { }

message SeekSpecified {
    uint64 number = 1;
}

message SeekPosition {
    oneof Type {
        SeekNewest newest = 1;
        SeekOldest oldest = 2;
        SeekSpecified specified = 3;
    }
}

message SeekInfo {
    enum SeekBehavior {
        BLOCK_UNTIL_READY = 0;
        FAIL_IF_NOT_READY = 1;
    }
    SeekPosition start = 1;    // The position to start the deliver from
    SeekPosition stop = 2;     // The position to stop the deliver
    SeekBehavior behavior = 3; // The behavior when a missing block is encountered
}

message DeliverResponse {
    oneof Type {
        common.Status status = 1;
        common.Block block = 2;
    }
}

service AtomicBroadcast {
    // broadcast receives a reply of Acknowledgement for each common.Envelope in order, indicating success or type of failure
    rpc Broadcast(stream common.Envelope) returns (stream BroadcastResponse) {}

    // deliver first requires an Envelope of type DELIVER_SEEK_INFO with Payload data as a mashaled SeekInfo message, then a stream of block replies is received.
    rpc Deliver(stream common.Envelope) returns (stream DeliverResponse) {}
}

```

**Comment by covereduser** [comment]
I have a same problem, did you find any solution?

**Comment by dredzone** [comment]
I have a same problem, did you find any solutions?

**Comment by haozipang** [comment]
you can test like this：
grpcc –i -d D:FF/ --proto ./helloworld.proto --address 127.0.0.1:50051
-d, --directory path to a protobuf file directory
-p, --proto path to a protobuf file describing the service (required)

tell the tool about the localtion of  file "ab.proto "

**Comment by l3ender** [comment]
It seems like the issue is trying to use a directory and multiple proto files. I was able to solve it by putting all protobuf definitions into one file.

**Comment by hayorov** [comment]
> all protobuf definitions into one file.

It worked!
