### ISSUE TITLE
Could not load file "[object Object]"

### ISSUE THREAD

**Issue by pavanyadav** [njpatel/grpcc#65]
grpcc --proto ./Users/pavankumar/Downloads/synchronicity.proto --address tingle-grpc.synchronicity.ai:443
Error: Could not load file "[object Object]"
    at Object.load (/Users/pavankumar/.npm-global/lib/node_modules/grpcc/node_modules/grpc/index.js:149:11)
    at Object.deprecated [as load] (internal/util.js:70:15)
    at createClient (/Users/pavankumar/.npm-global/lib/node_modules/grpcc/lib/index.js:57:21)
    at Object.<anonymous> (/Users/pavankumar/.npm-global/lib/node_modules/grpcc/bin/grpcc.js:35:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)

**Comment by HugeTimor** [comment]
I have a same problem. You can use relative path, it work for me.

**Comment by PS-StuartZahn** [comment]
`grpcc --proto common/protos/service.proto --directory common/protos --address domain.com:443`
Getting the same error with OSX.

**Comment by roman-lemko** [comment]
This error means grpcc couldn't locate the proto file.
Although I'd really like it to say `Error: Could not load file [FileName]` instead.
E.g. specifying filename instead of `[Object object]`

**Comment by haozipang** [comment]
you can test like this：
grpcc –i -d D:FF/ --proto ./helloworld.proto --address 127.0.0.1:50051
 -d, --directory <path>     path to a protobuf file directory   
 -p, --proto <path>         path to a protobuf file describing the service (required)
  
so maybe it is useful:
grpcc -d C:Users/pavankumar/Downloads/ --proto ./synchronicity.proto --address tingle-grpc.synchronicity.ai:443

**Comment by sitano** [comment]
does not work for proto with includes:

    $ grpcc -p ./api/grpc.proto -d ./api -a service:8000

**Comment by dylan-dinh** [comment]
> This error means grpcc couldn't locate the proto file.
> Although I'd really like it to say `Error: Could not load file [FileName]` instead.
> E.g. specifying filename instead of `[Object object]`

Just go to file index.js and add JSON.stringify(filename) basically it prints the object which contains the directory path and filepath

**Comment by dylan-dinh** [comment]
Using

`$ grpcc -p /Volumes/wholeDisk/libmed/ProtoObjects/postier.proto -d /Volumes/wholeDisk/libmed/ProtoObjects  -a 127.0.0.1:4000 -i`

print me out this error :
`Error: Could not load file "{"root":"/Volumes/wholeDisk/libmed/ProtoObjects","file":"/Volumes/wholeDisk/libmed/ProtoObjects/postier.proto"}"`

any tips ? Did everything above

**Comment by jlouazel** [comment]
Going way after the battle, but I made it work by launching the tool in the same folder as the proto file. Doing otherwise would just throw me the error.

Hope it can help someone. Enjoy 😄
