### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by gregzuro** [njpatel/grpcc#7]
```
16:51 $  node --harmony /usr/bin/grpcc

/usr/lib/node_modules/grpcc/lib/index.js:4
require('events').prototype.inspect = () => {return 'EventEmitter {}';};
                                       ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/grpcc/bin/grpcc.js:7:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Also, this won't run at all in Ubuntu: http://unix.stackexchange.com/questions/63979/shebang-line-with-usr-bin-env-command-argument-fails-on-linux

Above on ubuntu 14.04 and node 0.10.25

I tried it on OSX with node 0.10.18 and got the same thing.

**Comment by nathangoulding** [comment]
I couldn't get this working either and I'm not sure why. I fixed the issue with ES6, but then got another error with `forEach` and `lodash.js`.

I ended up just writing an alternative gRPC CLI: [nathangoulding/grpcli](https://github.com/nathangoulding/grpcli).
