### ISSUE TITLE
Lagom.GRPC with GRPCC: Error: 14 UNAVAILABLE: TCP Read failed

### ISSUE THREAD

**Issue by mgolovatiy-atconsulting-ru** [njpatel/grpcc#71]
Need help with some weird exception occured during testing grpc methods.

Testing `lagom-java-grpc-example` from `lagom/lagom-samples` repo, run ssl-lagom , then runAll command.
Http-GET requests via curl succeeded.
Tried to invoke grpc-method using grpcc.

```
grpcc --proto hello-impl/src/main/protobuf/helloworld.proto --insecure --address 127.0.0.1:11000 --eval 'client.sayHello({name:"Alice"}, printReply)'
```

Had exception.
Can connect to service, but when tried to invoke `client.sayHello("Alice", printReply)`  had the same exception.

Connecting:
```grpcc --proto hello-impl/src/main/protobuf/helloworld.proto --insecure --address 127.0.0.1:11000```
Connected:
```
Connecting to helloworld.GreeterService on 127.0.0.1:11000. Available globals:

  client - the client connection to GreeterService
    sayHello (HelloRequest, callback) returns HelloReply

  printReply - function to easily print a unary call reply (alias: pr)
  streamReply - function to easily print stream call replies (alias: sr)
  createMetadata - convert JS objects into grpc metadata instances (alias: cm)
  printMetadata - function to easily print a unary call's metadata (alias: pm)
```
When method invoked- exception:
```
Error:  { Error: 14 UNAVAILABLE: TCP Read failed
    at Object.exports.createStatusError (C:\Users\abcdef\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\common.js:91:15)
    at Object.onReceiveStatus (C:\Users\abcdef\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:1204:28)
    at InterceptingListener._callNext (C:\Users\abcdef\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (C:\Users\abcdef\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:618:8)
    at callback (C:\Users\abcdef\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:845:24) code: 14, metadata: {}, details: 'TCP Read failed' }
```
Also made my project on maven, mostly copied from sample (Maven 3.6.0, java 1.8, x64, Win7). 
Maven project consists of two artifacts- _api_ and _impl_.
Plugin section for `impl`-subproject:
SSL- configs are

```
      <plugin>
        <groupId>com.lightbend.lagom</groupId>
        <artifactId>lagom-maven-plugin</artifactId>
        <configuration>
          <lagomService>true</lagomService>
          <playService>true</playService>
          <serviceEnableSsl>true</serviceEnableSsl>
          <serviceHttpsPort>30443</serviceHttpsPort>
        </configuration>
      </plugin>
```
Code generator configs are

```
      <plugin>
        <groupId>com.lightbend.akka.grpc</groupId>
        <artifactId>akka-grpc-maven-plugin</artifactId>
        <version>${akka.grpc.version}</version>
        <configuration>
          <language>Java</language>
          <generateClient>true</generateClient>
          <generateServer>true</generateServer>
          <protoPaths>
            <protoPath>/src/main/protobuf</protoPath>
          </protoPaths>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

Have well-generated classes, added additionalRouter, service starts well.
Can connect grpcc to it. When invoke methods- have the same error. 

Is error in grpcc or may be some additional configuration needed?

**Comment by mgolovatiy-atconsulting-ru** [comment]
Grpcc must be started with SSL (without `--insecure` parameter). Lagom in `dev-mode` creates self-signed certificate (at  `./target/dev-mode/`), so for external CLIs u may need to generate `PEM`-file after started server:
```
keytool -export -alias sslconfig-selfsigned  -keystore target/dev-mode/selfsigned.keystore  -storepass "" -file trustedCA.crt
```
```
openssl x509 -in  trustedCA.crt -out trustedCA.pem -inform DER -outform PEM
```
Usage:
```
grpcc --proto <proto-path> --address localhost:<port> --root_cert <path>/trustedCA.pem   
```
