### ISSUE TITLE
Path prefix to server address

### ISSUE THREAD

**Issue by cartermckinnon** [njpatel/grpcc#73]
I run my gRPC services on Kubernetes using Envoy (via Ambassador) as an ingress proxy. My services are available at a URL like `localhost:80/my-service`. Is there a way to specify this path prefix to `grpcc`? I've tried `--address localhost:80/my-service` and I get a DNS resolution error:
```
Service@localhost:80/my-service> (node:66341) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

Error:  { Error: 14 UNAVAILABLE: DNS resolution failed
    at Object.exports.createStatusError (/Users/on0619/bin/node-v10.16.0-darwin-x64/lib/node_modules/grpcc/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/on0619/bin/node-v10.16.0-darwin-x64/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/on0619/bin/node-v10.16.0-darwin-x64/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/on0619/bin/node-v10.16.0-darwin-x64/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/on0619/bin/node-v10.16.0-darwin-x64/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:845:24) code: 14, metadata: {}, details: 'DNS resolution failed' }
```

**Comment by felipellrocha** [comment]
+1 I'm having the same issue

**Comment by cartermckinnon** [comment]
Closing this as I've just switched to using [`grpcurl`](https://github.com/fullstorydev/grpcurl).
