### ISSUE TITLE
fails with grpc-gateway endpoint annotations

### ISSUE THREAD

**Issue by tmc** [njpatel/grpcc#9]
Example:

```
Error: Parse error at line 136: illegal option name: (google.api.http).,
    at Error (native)
    at Parser.ProtoBuf.DotProto.ParserPrototype._parseOptionValue (/usr/local/lib/node_modules/grpcc/node_modules/protobufjs/dist/ProtoBuf.js:965:31)
    at Parser.ProtoBuf.DotProto.ParserPrototype._parseOption (/usr/local/lib/node_modules/grpcc/node_modules/protobufjs/dist/ProtoBuf.js:929:18)
    at Parser.ProtoBuf.DotProto.ParserPrototype._parseServiceRPC (/usr/local/lib/node_modules/grpcc/node_modules/protobufjs/dist/ProtoBuf.js:1046:30)
    at Parser.ProtoBuf.DotProto.ParserPrototype._parseService (/usr/local/lib/node_modules/grpcc/node_modules/protobufjs/dist/ProtoBuf.js:994:26)
    at Parser.ProtoBuf.DotProto.ParserPrototype.parse (/usr/local/lib/node_modules/grpcc/node_modules/protobufjs/dist/ProtoBuf.js:771:34)
    at Function.ProtoBuf.DotProto.Parser.parse (/usr/local/lib/node_modules/grpcc/node_modules/protobufjs/dist/ProtoBuf.js:795:39)
```

**Comment by njpatel** [comment]
Sorry, life's been crazy and I hadn't had a chance to work on grpcc for some time. Please reopen if this is still an issue on the latest version, there were some fixes contributed for nested package names.
